//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capyBIM.Resources.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tooltips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("capyBIM.Resources.Files.Tooltips", typeof(Tooltips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///Lorem ipsum
        ///
        ///Author: Iorhan Vendruscolo.
        /// </summary>
        internal static string ResourcesGitHub {
            get {
                return ResourceManager.GetString("ResourcesGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///Lorem ipsum
        ///
        ///Author: Iorhan Vendruscolo.
        /// </summary>
        internal static string ResourcesIn {
            get {
                return ResourceManager.GetString("ResourcesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///Lorem ipsum
        ///
        ///Author: Iorhan Vendruscolo.
        /// </summary>
        internal static string ResourcesRVTDocs {
            get {
                return ResourceManager.GetString("ResourcesRVTDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///Rotate selected elements to specified angle.
        ///
        ///Author: Iorhan Vendruscolo .
        /// </summary>
        internal static string ToolsRotate {
            get {
                return ResourceManager.GetString("ToolsRotate", resourceCulture);
            }
        }
    }
}
